# Generated by Django 6.0.7 on 2026-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile', models.ImageField(upload_to='profile/')),
                ('maharat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bazeh_zamani', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('mesal', models.TextField()),
            ],
        ),
    ]
