# Generated by Django 6.0.7 on 2026-07-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezoomeh_abzar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imoji',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
