# Generated by Django 6.0.7 on 2026-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rezoomeh_abzar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('fanavaries', models.ManyToManyField(related_name='sits', to='rezoomeh_abzar_app.fanavary')),
            ],
        ),
    ]
