# Generated by Django 6.0.7 on 2026-07-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezoomeh_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='demo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
